import crypto from "node:crypto";
import { hashLcmPayload, type RawEntry } from "../storage/lcm-identity.js";
import type { LcmLedger } from "../storage/lcm-ledger.js";
import { buildLcmPrompt, emergencyReduce, type LcmModelResult, type LcmSummarizer } from "./lcm-model.js";

type LcmNodeState = "pending" | "ready" | "running" | "failed";
type LcmJobState = "pending" | "running" | "completed" | "failed";
export interface LcmSourceRef { sessionId: string; entryId: string; revision: number; payloadHash: string; }
type RawSourceRef = LcmSourceRef;
export interface LcmNode { nodeId: string; projectKey: string; sessionId: string; branch: string | null; kind: "leaf" | "condensed"; sources: LcmSourceRef[]; children: string[]; depth: number; sourceHash: string; policyHash: string; modelHash: string; state: LcmNodeState; text?: string; createdAt: number; }
export interface LcmJob { jobId: string; projectKey: string; nodeId: string; priority: number; eligibleAt: number; state: LcmJobState; ownerId?: string; leaseToken?: string; leaseUntil?: number; attempts: number; nextRetryAt: number; error?: string; createdAt: number; updatedAt: number; }
export interface LcmBudget { calls: number; inputTokens: number; outputTokens: number; cost: number; wallMs: number; }
export interface LcmBudgetPolicy extends LcmBudget { sessionCalls: number; }
const DEFAULT_LCM_BUDGET: LcmBudgetPolicy = { calls: 512, inputTokens: 64_000_000, outputTokens: 4_000_000, cost: Number.POSITIVE_INFINITY, wallMs: 7_200_000, sessionCalls: 256 };
export interface LcmMaintenanceOptions { now?: () => number; ownerId?: string; policyHash?: string; maxLeafEntries?: number; maxCondenseChildren?: number; maxInputChars?: number; maxOutputChars?: number; budget?: Partial<LcmBudgetPolicy>; }
const hash = (v: unknown) => hashLcmPayload(v);
const parse = <T>(v: unknown): T => JSON.parse(String(v));
const rawHash = (e: RawEntry) => e.payloadHash;
const token = () => crypto.randomUUID();

export class LcmMaintenance {
  readonly projectKey: string;
  private readonly now: () => number;
  private readonly ownerId: string;
  private readonly policyHash: string;
  private readonly maxLeaf: number;
  private readonly maxChildren: number;
  private readonly maxInputChars: number;
  private readonly maxOutputChars: number;
  private readonly budget: LcmBudgetPolicy;
  constructor(private readonly ledger: LcmLedger, options: LcmMaintenanceOptions = {}) { this.projectKey = ledger.project.key; this.now = options.now ?? Date.now; this.ownerId = options.ownerId ?? crypto.randomUUID(); this.policyHash = options.policyHash ?? hash("lcm-policy-v1"); this.maxLeaf = options.maxLeafEntries ?? 32; this.maxChildren = options.maxCondenseChildren ?? 4; this.maxInputChars = options.maxInputChars ?? 200_000; this.maxOutputChars = options.maxOutputChars ?? 4_096; this.budget = { ...DEFAULT_LCM_BUDGET, ...options.budget }; }
  listNodes(limit = 100): LcmNode[] { return this.ledger.readOnly(db => (db.prepare("SELECT payload FROM summary_nodes WHERE project_key=? ORDER BY created_at,node_id LIMIT ?").all(this.projectKey, limit) as Array<{payload:string}>).map(r => { const node = parse<LcmNode>(r.payload); if (node.projectKey !== this.projectKey) throw new Error("node project does not match ledger project"); return node; })); }
  getNode(nodeId: string): LcmNode | undefined { return this.ledger.readOnly(db => { const row = db.prepare("SELECT payload FROM summary_nodes WHERE node_id=? AND project_key=?").get(nodeId, this.projectKey) as {payload?:string}|undefined; if (!row?.payload) return undefined; const node = parse<LcmNode>(row.payload); if (node.projectKey !== this.projectKey) throw new Error("node project does not match ledger project"); return node; }); }
  getFrontier(sessionId?: string, branch?: string | null, activeSources?: ReadonlySet<string>): LcmNode[] { const nodes=this.listNodes(100000).filter(n => n.state === "ready" && n.policyHash === this.policyHash && (!sessionId || n.sessionId === sessionId) && (branch === undefined || n.branch === branch || n.branch === null) && (!activeSources || n.sources.every(s => activeSources.has(this.sourceKey(s))))) ; const covered=new Set(nodes.flatMap(n=>n.children)); return nodes.filter(n=>!covered.has(n.nodeId)); }
  listJobs(limit = 100): LcmJob[] { return this.ledger.readOnly(db => (db.prepare("SELECT payload FROM maintenance_jobs WHERE project_key=? ORDER BY created_at,job_id LIMIT ?").all(this.projectKey, limit) as Array<{payload:string}>).map(r => { const job = parse<LcmJob>(r.payload); if (job.projectKey !== this.projectKey) throw new Error("job project does not match ledger project"); return job; })); }
  selectLeaf(entries = this.ledger.readRaw(this.projectKey), branch?: string | null): RawEntry[] { const first = entries[0]; if (!first) return []; const nodes = this.listNodes(100000).filter(n => n.state !== "failed" && n.policyHash === this.policyHash && n.sessionId === first.sessionId && (branch === undefined || n.branch === branch || n.branch === null)); const covered = new Set(nodes.flatMap(n => n.sources.map(s => this.sourceKey(s)))); const candidates = entries.filter(e => e.sessionId === first.sessionId && (branch === undefined || e.branch === branch || e.branch === null) && !covered.has(this.sourceKey(e))); const picked: RawEntry[] = []; let chars = 0; for (const entry of candidates) { if (picked.length >= this.maxLeaf) break; const size = entry.payloadJson.length; if (picked.length > 0 && chars + size > this.maxInputChars) break; picked.push(entry); chars += size; } return picked; }
  selectCondensation(sessionId?: string, activeSources?: ReadonlySet<string>, branch?: string | null): LcmNode[] { const nodes = this.listNodes(100000).filter(n => n.state === "ready" && n.policyHash === this.policyHash && (!sessionId || n.sessionId === sessionId) && (!activeSources || n.sources.every(s => activeSources.has(this.sourceKey(s)))) && (branch === undefined || n.branch === branch || n.branch === null)); const eligible = new Set(nodes.map(n => n.nodeId)); const edges = this.ledger.readOnly(db => db.prepare("SELECT e.parent_id,e.child_id FROM summary_edges e JOIN summary_nodes parent ON parent.node_id=e.parent_id AND parent.project_key=? JOIN summary_nodes child ON child.node_id=e.child_id AND child.project_key=parent.project_key WHERE parent.project_key=?").all(this.projectKey, this.projectKey) as Array<{parent_id:string;child_id:string}>); const consumed = new Set(edges.filter(e => eligible.has(e.parent_id)).map(e => e.child_id)); const candidates = nodes.filter(n => !consumed.has(n.nodeId)); const first = candidates[0]; if (!first) return []; const depth = Math.min(...candidates.map(n => n.depth)); const sameDepth = candidates.filter(n => n.depth === depth); if (depth > 0 && sameDepth.length < 2) return []; return candidates.filter(n => n.projectKey === first.projectKey && n.sessionId === first.sessionId && n.depth === depth).sort((a,b) => a.nodeId.localeCompare(b.nodeId)).slice(0, this.maxChildren); }
  createLeaf(entries = this.selectLeaf()): LcmNode | undefined { if (!entries.length) return undefined; const branches = new Set(entries.map(entry => entry.branch).filter((value): value is string => typeof value === "string")); if (branches.size > 1) throw new Error("cross-branch ranges"); const branch = [...branches][0] ?? null; const source = entries.map((e, index) => { if (e.projectKey !== this.projectKey) throw new Error("entry project does not match ledger project"); const payload = parse<{type?: unknown; id?: unknown}>(e.payloadJson); if (typeof payload.type !== "string" || !payload.type || payload.id !== e.entryId) throw new Error("invalid raw payload"); if (hash(payload) !== rawHash(e)) throw new Error("payload hash mismatch"); return { sessionId:e.sessionId, entryId:e.entryId, revision:e.revision, payloadHash:rawHash(e) }; }); this.validateSources(source); const node: LcmNode = { nodeId:`leaf:${hash({ projectKey:this.projectKey, source, branch, policyHash:this.policyHash })}`, projectKey:this.projectKey, sessionId:entries[0]!.sessionId, branch, kind:"leaf", sources:source, children:[], depth:0, sourceHash:hash(source.map(s=>s.payloadHash)), policyHash:this.policyHash, modelHash:"", state:"pending", createdAt:this.now() }; this.publish(node); return node; }
  createCondensed(children = this.selectCondensation()): LcmNode | undefined { if (!children.length) return undefined; if (children.some(c => c.state !== "ready")) throw new Error("condensation requires ready children"); if (new Set(children.map(c=>c.sessionId)).size !== 1 || new Set(children.map(c=>c.depth)).size !== 1) throw new Error("cross-branch ranges"); const storedChildren = children.map((child) => this.getNode(child.nodeId)); if (storedChildren.some((child) => !child || child.projectKey !== this.projectKey)) throw new Error("child project does not match ledger project"); if (storedChildren.some((child, index) => JSON.stringify(child) !== JSON.stringify(children[index]))) throw new Error("child payload changed"); const concreteBranches = new Set(storedChildren.map(c => c!.branch).filter((value): value is string => typeof value === "string")); if (concreteBranches.size > 1) throw new Error("cross-branch ranges"); const branch = [...concreteBranches][0] ?? null; const source = [...new Map(storedChildren.flatMap(c => c!.sources).map((value) => [this.sourceKey(value), value])).values()]; this.validateSources(source); const node: LcmNode = { nodeId:`condensed:${hash({ projectKey:this.projectKey, children:storedChildren.map(c=>c!.nodeId), branch, policyHash:this.policyHash })}`, projectKey:this.projectKey, sessionId:children[0]!.sessionId, branch, kind:"condensed", sources:source, children:children.map(c=>c.nodeId), depth:Math.max(...children.map(c=>c.depth))+1, sourceHash:hash(children.map(c=>c.sourceHash)), policyHash:this.policyHash, modelHash:"", state:"pending", createdAt:this.now() }; this.publish(node); return node; }
  private validateSources(source: LcmSourceRef[]) { const seen = new Set<string>(); for (const s of source) { if (seen.has(this.sourceKey(s))) throw new Error("duplicate source identity"); seen.add(this.sourceKey(s)); } if (new Set(source.map(s => s.sessionId)).size !== 1) throw new Error("cross-session ranges"); }
  private sourceKey(source: Pick<LcmSourceRef, "sessionId" | "entryId" | "revision">) { return `${source.sessionId}:${source.entryId}:${source.revision}`; }
  private publish(node: LcmNode) { this.ledger.transaction(db => { if (node.children.includes(node.nodeId)) throw new Error("cycle"); for (const child of node.children) if (!db.prepare("SELECT 1 FROM summary_nodes WHERE node_id=? AND project_key=?").get(child,this.projectKey)) throw new Error("missing child"); db.prepare("INSERT OR IGNORE INTO summary_nodes(node_id,project_key,payload,created_at) VALUES(?,?,?,?)").run(node.nodeId,this.projectKey,JSON.stringify(node),node.createdAt); for (const child of node.children) db.prepare("INSERT OR IGNORE INTO summary_edges(parent_id,child_id) VALUES(?,?)").run(node.nodeId,child); const job = this.job(node); db.prepare("INSERT OR IGNORE INTO maintenance_jobs(job_id,project_key,status,payload,created_at,updated_at) VALUES(?,?,?,?,?,?)").run(job.jobId,this.projectKey,job.state,JSON.stringify(job),job.createdAt,job.updatedAt); }); }
  private job(node:LcmNode): LcmJob { const t=this.now(); return {jobId:`job:${node.nodeId}`,projectKey:this.projectKey,nodeId:node.nodeId,priority:node.kind === "condensed" ? 20 : 10,eligibleAt:t,state:"pending",attempts:0,nextRetryAt:t,createdAt:t,updatedAt:t}; }
  claim(jobId: string, ownerId = this.ownerId): LcmJob { return this.ledger.transaction(db => { const row = db.prepare("SELECT payload FROM maintenance_jobs WHERE job_id=? AND project_key=?").get(jobId,this.projectKey) as {payload?:string}|undefined; if (!row?.payload) throw new Error("job not found"); const old=parse<LcmJob>(row.payload); if (old.projectKey !== this.projectKey) throw new Error("job project does not match ledger project"); const t=this.now(); const expired = old.state === "running" && (old.leaseUntil ?? 0) <= t; if (old.state === "running" && !expired) throw new Error("job lease held"); if ((old.state !== "pending" && !expired) || old.eligibleAt > t || old.nextRetryAt > t) throw new Error("job not eligible"); const active = (db.prepare("SELECT payload FROM maintenance_jobs WHERE project_key=? AND status=?").all(this.projectKey, "running") as Array<{payload:string}>).map(r => parse<LcmJob>(r.payload)).filter(j => j.jobId !== old.jobId && (j.leaseUntil ?? 0) > t); if (active.length) throw new Error("project lease held"); const nodeRow = db.prepare("SELECT payload FROM summary_nodes WHERE node_id=? AND project_key=?").get(old.nodeId,this.projectKey) as {payload?:string}|undefined; const sessionId = nodeRow?.payload ? parse<LcmNode>(nodeRow.payload).sessionId : ""; const day = this.day(t); const projectUsage = this.usage(db, day); const sessionUsage = this.usage(db, day, sessionId); if (projectUsage.calls >= this.budget.calls || projectUsage.inputTokens >= this.budget.inputTokens || projectUsage.outputTokens >= this.budget.outputTokens || projectUsage.cost >= this.budget.cost || projectUsage.wallMs >= this.budget.wallMs || sessionUsage.calls >= this.budget.sessionCalls) throw new Error("budget exhausted"); const out={...old,state:"running" as const,ownerId,leaseToken:token(),leaseUntil:t+30_000,updatedAt:t}; db.prepare("UPDATE maintenance_jobs SET status=?,payload=?,updated_at=? WHERE job_id=? AND project_key=?").run(out.state,JSON.stringify(out),t,jobId,this.projectKey); return out; }); }
  claimEmergency(jobId: string, ownerId = this.ownerId): LcmJob { return this.ledger.transaction(db => { const row = db.prepare("SELECT payload FROM maintenance_jobs WHERE job_id=? AND project_key=?").get(jobId,this.projectKey) as {payload?:string}|undefined; if (!row?.payload) throw new Error("job not found"); const old = parse<LcmJob>(row.payload); if (old.projectKey !== this.projectKey) throw new Error("job project does not match ledger project"); const t = this.now(); const expired = old.state === "running" && (old.leaseUntil ?? 0) <= t; if (old.state === "running" && !expired) throw new Error("job lease held"); if (old.state === "completed") throw new Error("job already completed"); const out = { ...old, state: "running" as const, ownerId, leaseToken: token(), leaseUntil: t + 30_000, updatedAt: t }; db.prepare("UPDATE maintenance_jobs SET status=?,payload=?,updated_at=? WHERE job_id=? AND project_key=?").run(out.state,JSON.stringify(out),t,jobId,this.projectKey); return out; }); }
  renew(job:LcmJob): LcmJob { return this.fenced(job, old => ({...old,leaseUntil:this.now()+30_000,updatedAt:this.now()})); }
  private validateText(text: unknown): asserts text is string { if (typeof text !== "string" || text.length === 0) throw new Error("invalid summary text"); let length = 0; for (const _ of text) { length += 1; if (length > this.maxOutputChars) throw new Error("summary exceeds output bound"); } }
  complete(job:LcmJob, result:LcmModelResult): LcmNode { this.validateText(result.text); return this.ledger.transaction(db => { const current=this.readJob(db,job.jobId); this.assertLease(current,job); if (current.nodeId !== job.nodeId) throw new Error("job node mismatch"); const row=db.prepare("SELECT payload FROM summary_nodes WHERE node_id=? AND project_key=?").get(job.nodeId,this.projectKey) as {payload?:string}|undefined; if (!row?.payload) throw new Error("node not found"); const node=parse<LcmNode>(row.payload); if (node.projectKey !== this.projectKey || node.nodeId !== current.nodeId) throw new Error("node project does not match ledger project"); for (const source of node.sources) { const raw=db.prepare("SELECT payload_json,session_id FROM raw_entries WHERE project_key=? AND session_id=? AND entry_id=? AND revision=?").get(this.projectKey,source.sessionId,source.entryId,source.revision) as {payload_json?:string;session_id?:string}|undefined; if (!raw?.payload_json || hash(parse(raw.payload_json)) !== source.payloadHash || raw.session_id !== source.sessionId) throw new Error("stale source"); } if (![result.inputTokens,result.outputTokens,result.cost,result.wallMs].every((value) => Number.isFinite(value) && value >= 0)) throw new Error("invalid model usage"); const projectUsage = this.usage(db, this.day(this.now())); const sessionUsage = this.usage(db, this.day(this.now()), node.sessionId); if (projectUsage.calls + 1 > this.budget.calls || projectUsage.inputTokens + result.inputTokens > this.budget.inputTokens || projectUsage.outputTokens + result.outputTokens > this.budget.outputTokens || projectUsage.cost + result.cost > this.budget.cost || projectUsage.wallMs + result.wallMs > this.budget.wallMs || sessionUsage.calls + 1 > this.budget.sessionCalls) throw new Error("budget exhausted"); const out={...node,state:"ready" as const,text:result.text,modelHash:result.modelHash}; this.account(db,node.sessionId,result); db.prepare("UPDATE summary_nodes SET payload=? WHERE node_id=? AND project_key=?").run(JSON.stringify(out),node.nodeId,this.projectKey); const { ownerId: _ownerId, leaseToken: _leaseToken, leaseUntil: _leaseUntil, ...base } = current; const done={...base,state:"completed" as const,updatedAt:this.now()}; db.prepare("UPDATE maintenance_jobs SET status=?,payload=?,updated_at=? WHERE job_id=? AND project_key=?").run(done.state,JSON.stringify(done),done.updatedAt,done.jobId,this.projectKey); return out; }); }
  completeEmergency(job:LcmJob, text:string): LcmNode { this.validateText(text); return this.ledger.transaction(db => { const current=this.readJob(db,job.jobId); this.assertLease(current,job); if (current.nodeId !== job.nodeId) throw new Error("job node mismatch"); const row=db.prepare("SELECT payload FROM summary_nodes WHERE node_id=? AND project_key=?").get(job.nodeId,this.projectKey) as {payload?:string}|undefined; if (!row?.payload) throw new Error("node not found"); const node=parse<LcmNode>(row.payload); if (node.projectKey !== this.projectKey || node.nodeId !== current.nodeId) throw new Error("node project does not match ledger project"); for (const source of node.sources) { const raw=db.prepare("SELECT payload_json,session_id FROM raw_entries WHERE project_key=? AND session_id=? AND entry_id=? AND revision=?").get(this.projectKey,source.sessionId,source.entryId,source.revision) as {payload_json?:string;session_id?:string}|undefined; if (!raw?.payload_json || hash(parse(raw.payload_json)) !== source.payloadHash || raw.session_id !== source.sessionId) throw new Error("stale source"); } const out={...node,state:"ready" as const,text,modelHash:"emergency"}; db.prepare("UPDATE summary_nodes SET payload=? WHERE node_id=? AND project_key=?").run(JSON.stringify(out),node.nodeId,this.projectKey); const { ownerId: _ownerId, leaseToken: _leaseToken, leaseUntil: _leaseUntil, ...base } = current; const done={...base,state:"completed" as const,updatedAt:this.now()}; db.prepare("UPDATE maintenance_jobs SET status=?,payload=?,updated_at=? WHERE job_id=? AND project_key=?").run(done.state,JSON.stringify(done),done.updatedAt,done.jobId,this.projectKey); return out; }); }
  fail(job:LcmJob,error:string): LcmJob { return this.fenced(job, old => { const attempts=old.attempts+1; const delay=Math.min(900_000,30_000*2**(attempts-1)); const { ownerId: _ownerId, leaseToken: _leaseToken, leaseUntil: _leaseUntil, ...base } = old; return {...base,attempts,error,state:attempts>=3?"failed":"pending",eligibleAt:this.now()+delay,nextRetryAt:this.now()+delay,updatedAt:this.now()}; }); }
  async run(job:LcmJob, model:LcmSummarizer, input:string, signal=new AbortController().signal): Promise<LcmNode> { let sources: LcmSourceRef[] = []; let claimed: LcmJob | undefined; const controller = new AbortController(); let renew: ReturnType<typeof setInterval> | undefined; const timer = setTimeout(() => controller.abort(), 60_000); const abort = () => controller.abort(); signal.addEventListener("abort", abort, { once: true }); try { claimed=this.claim(job.jobId,job.ownerId ?? this.ownerId); const node=this.getNode(claimed.nodeId); sources=node?.sources ?? []; renew = setInterval(() => { try { if (claimed) claimed = this.renew(claimed); } catch {} }, 10_000); const result=await Promise.race([model.generate({prompt:buildLcmPrompt(node?.kind ?? "leaf",input,this.maxInputChars),sessionId:node?.sessionId ?? "",signal:controller.signal}), new Promise<never>((_, reject) => controller.signal.addEventListener("abort", () => reject(new Error("LCM timeout")), { once: true }))]); return this.complete(claimed,result); } catch (error) { if (!claimed) throw error; const fallback=emergencyReduce(input,this.maxOutputChars,sources); try { return this.completeEmergency(claimed,fallback); } catch { try { this.fail(claimed,String(error)); } catch {} throw error; } } finally { clearTimeout(timer); if (renew) clearInterval(renew); signal.removeEventListener("abort", abort); } }
  private day(ms:number): string { return new Date(ms).toISOString().slice(0,10); }
  private usage(db:any, day:string, sessionId?:string): LcmBudget { const q = sessionId === undefined ? "SELECT COALESCE(SUM(calls),0) calls,COALESCE(SUM(input_tokens),0) inputTokens,COALESCE(SUM(output_tokens),0) outputTokens,COALESCE(SUM(cost),0) cost,COALESCE(SUM(wall_ms),0) wallMs FROM maintenance_usage WHERE project_key=? AND day=?" : "SELECT COALESCE(SUM(calls),0) calls,COALESCE(SUM(input_tokens),0) inputTokens,COALESCE(SUM(output_tokens),0) outputTokens,COALESCE(SUM(cost),0) cost,COALESCE(SUM(wall_ms),0) wallMs FROM maintenance_usage WHERE project_key=? AND day=? AND session_id=?"; const r=(sessionId === undefined ? db.prepare(q).get(this.projectKey,day) : db.prepare(q).get(this.projectKey,day,sessionId)) as LcmBudget; return r; }
  private account(db:any, sessionId:string, result:LcmModelResult) { const d=this.day(this.now()); db.prepare("INSERT INTO maintenance_usage(project_key,day,session_id,calls,input_tokens,output_tokens,cost,wall_ms) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(project_key,day,session_id) DO UPDATE SET calls=calls+excluded.calls,input_tokens=input_tokens+excluded.input_tokens,output_tokens=output_tokens+excluded.output_tokens,cost=cost+excluded.cost,wall_ms=wall_ms+excluded.wall_ms").run(this.projectKey,d,sessionId,1,result.inputTokens,result.outputTokens,result.cost,result.wallMs); }
  private readJob(db: any,id:string):LcmJob { const row=db.prepare("SELECT payload FROM maintenance_jobs WHERE job_id=? AND project_key=?").get(id,this.projectKey) as {payload:string}|undefined; if(!row) throw new Error("job not found"); const job=parse<LcmJob>(row.payload); if(job.projectKey!==this.projectKey) throw new Error("job project does not match ledger project"); return job; }
  private assertLease(current:LcmJob, expected:LcmJob) { if(current.ownerId!==expected.ownerId || current.leaseToken!==expected.leaseToken || current.state!=="running" || (current.leaseUntil??0)<this.now()) throw new Error("lease fenced"); }
  private fenced(job:LcmJob, update:(old:LcmJob)=>LcmJob):LcmJob { return this.ledger.transaction(db => { const old=this.readJob(db,job.jobId); this.assertLease(old,job); const out=update(old); db.prepare("UPDATE maintenance_jobs SET status=?,payload=?,updated_at=? WHERE job_id=? AND project_key=?").run(out.state,JSON.stringify(out),out.updatedAt,out.jobId,this.projectKey); return out; }); }
}
