import { afterEach, describe, expect, it } from "vitest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createDeleteConfirmationToken, LcmLedger, canonicalProjectIdentity, hashLcmPayload } from "../../src/storage/lcm-ledger.js";

const dirs: string[] = [];
const make = () => { const d = fs.mkdtempSync(path.join(os.tmpdir(), "lcm-ledger-")); dirs.push(d); return d; };
afterEach(() => { for (const d of dirs.splice(0)) fs.rmSync(d, { recursive: true, force: true }); });
const entry = (projectKey: string, content: string, entryId = "e1") => ({ projectKey, sessionId: "s1", entryId, role: "user", content, payloadJson: JSON.stringify({ type: "message", id: entryId, role: "user", content, parentId: null, branchId: "main", timestamp: 1 }) });

describe("LCM ledger", () => {
  it("is idempotent and creates immutable revisions", () => { const d = make(); const l = new LcmLedger({ dbPath: path.join(d,"a.sqlite"), project: { liveCwd: d } }); const a = l.appendRaw(entry(l.project.key,"one")); expect(l.appendRaw(entry(l.project.key,"one"))).toEqual(a); const b = l.appendRaw(entry(l.project.key,"two")); expect(b.revision).toBe(2); expect(l.readRaw()).toHaveLength(2); l.close(); });
  it("hashes the full canonical payload, not derived content", () => { const d = make(); const l = new LcmLedger({ dbPath: path.join(d,"a.sqlite"), project: { liveCwd: d } }); const first = l.appendRaw(entry(l.project.key,"same","e1")); const second = l.appendRaw({ ...entry(l.project.key,"same","e1"), payloadJson: JSON.stringify({ timestamp: 2, content: "same", role: "user", id: "e1", type: "message" }) }); expect(second.revision).toBe(2); expect(first.payloadHash).toBe(hashLcmPayload(JSON.parse(first.payloadJson))); expect(second.payloadHash).not.toBe(first.payloadHash); l.close(); });
  it("rolls back an append batch atomically and preserves restart integrity", () => { const d=make(); const p=path.join(d,"a.sqlite"); let l=new LcmLedger({dbPath:p,project:{liveCwd:d}}); expect(() => l.transaction(() => { l.appendRaw(entry(l.project.key,"first","e1")); l.appendRaw(entry(l.project.key,"second","e2")); throw new Error("batch abort"); })).toThrow("batch abort"); expect(l.readRaw()).toHaveLength(0); l.close(); l=new LcmLedger({dbPath:p,project:{liveCwd:d}}); const saved=l.appendRaw(entry(l.project.key,"persisted","e1")); l.close(); l=new LcmLedger({dbPath:p,project:{liveCwd:d}}); expect(l.readRaw()).toHaveLength(1); expect(l.readRaw()[0]).toMatchObject(saved); l.close(); });
  it("rolls back transaction primitives and reopens", () => { const d = make(); const p = path.join(d,"a.sqlite"); let l = new LcmLedger({ dbPath:p, project:{liveCwd:d}}); expect(() => l.transaction(db => { db.prepare("INSERT INTO summary_nodes(node_id,project_key,payload,created_at) VALUES(?,?,?,?)").run("n",l.project.key,"x",Date.now()); throw new Error("abort"); })).toThrow("abort"); l.close(); l = new LcmLedger({dbPath:p,project:{liveCwd:d}}); expect((l.db.prepare("SELECT count(*) n FROM summary_nodes").get() as {n:number}).n).toBe(0); l.close(); });
  it("uses recorded cwd and converges aliases while separating worktrees", () => { const d=make(); const real=path.join(d,"real"); fs.mkdirSync(real); const alias=path.join(d,"alias"); fs.symlinkSync(real,alias); expect(canonicalProjectIdentity({recordedCwd:alias,liveCwd:"/nope"}).key).toBe(canonicalProjectIdentity({liveCwd:real}).key); const other=path.join(d,"other"); fs.mkdirSync(other); expect(canonicalProjectIdentity({liveCwd:other}).key).not.toBe(canonicalProjectIdentity({liveCwd:real}).key); });
  it("rejects missing entry IDs", () => { const d=make(); const l=new LcmLedger({dbPath:path.join(d,"a.sqlite"),project:{liveCwd:d}}); expect(() => l.appendRaw({projectKey:l.project.key,sessionId:"s",entryId:"  ",role:"user",content:"x",payloadJson: JSON.stringify({ type: "message", id: "  ", role: "user", content: "x" })})).toThrow("entry ID is required"); expect(l.readRaw()).toHaveLength(0); l.close(); });
  it("serializes concurrent appends", async () => { const d=make(); const l=new LcmLedger({dbPath:path.join(d,"a.sqlite"),project:{liveCwd:d}}); const out=await Promise.all(Array.from({length:8},(_,i)=>l.serialize(()=>l.appendRaw(entry(l.project.key,String(i),`e${i}`))))); expect(out).toHaveLength(8); expect(l.readRaw()).toHaveLength(8); l.close(); });
  it("rejects cross-project raw reads", () => { const d=make(); const l=new LcmLedger({dbPath:path.join(d,"a.sqlite"),project:{liveCwd:d}}); const stored=l.appendRaw(entry(l.project.key,"session")); expect(() => l.readRaw("other-project")).toThrow("project key does not match ledger project"); expect(() => l.readRawPage("other-project")).toThrow("project key does not match ledger project"); expect(() => l.readRawEntry("other-project",stored.sessionId,stored.entryId,stored.revision)).toThrow("project key does not match ledger project"); l.close(); });
  it("reports checkpoint mode and operational state", () => { const d=make(); const l=new LcmLedger({dbPath:path.join(d,"a.sqlite"),project:{liveCwd:d},warningBytes:1,maintenanceBytes:2}); const passive=l.checkpoint(); expect(passive.mode).toBe("passive"); expect(passive.busy).toBeGreaterThanOrEqual(0); expect(passive.logPages).toBeGreaterThanOrEqual(0); expect(passive.checkpointedPages).toBeGreaterThanOrEqual(0); expect(passive.truncated).toBe(false); const truncate=l.checkpoint("truncate"); expect(truncate.mode).toBe("truncate"); expect(truncate.truncated).toBe(truncate.busy === 0 && truncate.logPages === 0); expect(l.operationalState).toBe("maintenance"); l.markDegraded(); expect(l.operationalState).toBe("degraded"); expect(() => l.readRaw()).toThrow("ledger is degraded"); l.close(); });
  it("deletes project-owned edges and usage after verified backup", () => { const d=make(); const db=path.join(d,"a.sqlite"); const backup=path.join(d,"backup.sqlite"); const l=new LcmLedger({dbPath:db,project:{liveCwd:d}}); l.appendRaw(entry(l.project.key,"keep")); l.transaction(database => { database.prepare("INSERT INTO summary_nodes(node_id,project_key,payload,created_at) VALUES(?,?,?,?)").run("n1",l.project.key,"{}",1); database.prepare("INSERT INTO summary_nodes(node_id,project_key,payload,created_at) VALUES(?,?,?,?)").run("n2",l.project.key,"{}",1); database.prepare("INSERT INTO summary_edges(parent_id,child_id) VALUES(?,?)").run("n2","n1"); database.prepare("INSERT INTO maintenance_usage(project_key,day,session_id,calls,input_tokens,output_tokens,cost,wall_ms) VALUES(?,?,?,?,?,?,?,?)").run(l.project.key,"2026-09-01","s1",1,2,3,0,4); }); const manifest=l.backup(backup); l.deleteProject(createDeleteConfirmationToken(l.project.key),manifest); expect((l.db.prepare("SELECT count(*) n FROM summary_edges").get() as {n:number}).n).toBe(0); expect((l.db.prepare("SELECT count(*) n FROM maintenance_usage").get() as {n:number}).n).toBe(0); expect((l.db.prepare("SELECT count(*) n FROM projects").get() as {n:number}).n).toBe(0); l.close(); });
  it("creates a verified backup and requires a typed delete token", () => { const d=make(); const db=path.join(d,"a.sqlite"); const backup=path.join(d,"backup.sqlite"); const l=new LcmLedger({dbPath:db,project:{liveCwd:d}}); l.appendRaw(entry(l.project.key,"keep")); const manifest=l.backup(backup); expect(manifest.format).toBe("lcm-ledger-backup"); expect(manifest.version).toBe(1); expect(manifest.integrity).toBe("ok"); expect(manifest.rowCounts.raw_entries).toBe(1); expect(manifest.rowCounts.maintenance_usage).toBe(0); expect(fs.statSync(backup).mode & 0o777).toBe(0o600); expect(fs.statSync(`${backup}.manifest.json`).mode & 0o777).toBe(0o600); expect(() => l.deleteProject({projectKey:l.project.key,value:"bad",__brand:"DeleteConfirmationToken"},manifest)).toThrow("invalid delete confirmation token"); l.deleteProject(createDeleteConfirmationToken(l.project.key),manifest); expect(l.readRaw()).toHaveLength(0); expect(fs.existsSync(`${backup}.delete-manifest.json`)).toBe(true); l.close(); });
  it("rejects deletion after a post-backup WAL write", () => { const d=make(); const db=path.join(d,"a.sqlite"); const backup=path.join(d,"backup.sqlite"); const l=new LcmLedger({dbPath:db,project:{liveCwd:d}}); l.appendRaw(entry(l.project.key,"before")); const manifest=l.backup(backup); l.appendRaw(entry(l.project.key,"after")); expect(() => l.deleteProject(createDeleteConfirmationToken(l.project.key),manifest)).toThrow("backup verification failed"); l.close(); });
});
